services:
  papelariaonline:
    image: papelariaonline
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
    command: ["npm", "run", "dev", "--", "--hostname", "0.0.0.0"]
